// Login Actions
export const SET_LOGIN = 'SRC/REDUX/LOGIN/SET_LOGIN';
export const SET_LOGOUT = 'SRC/REDUX/LOGIN/SET_LOGOUT';

// Validation Actions
export const VALIDATION_INPUT = 'SRC/ACTIONS/VALIDATIONACTION/VALIDATION_INPUT';

// Request actions
export const CALL_REQUEST = 'SRC/ACTIONS/CALL_REQUEST';
export const START_REQUEST = 'SRC/ACTIONS/START_REQUEST';
export const DONE_REQUEST = 'SRC/ACTIONS/DONE_REQUEST';

// Fetch Account
export const FETCH_ACCOUNT_LIST = "SRC/ACTIONS/FETCH_ACCOUNT_LIST";
export const FETCH_ACCOUNT_LIST_SUCCESS = "SRC/ACTIONS/FETCH_ACCOUNT_LIST_SUCCESS";
export const FETCH_ACCOUNT_LIST_FAILURE = "SRC/ACTIONS/FETCH_ACCOUNT_LIST_FAILURE";
export const LOAD_MORE_ACCOUNT = "SRC/ACTIONS/LOAD_MORE_ACCOUNT";
export const LOAD_MORE_ACCOUNT_SUCCEED = "SRC/ACTIONS/LOAD_MORE_ACCOUNT_SUCCEED";
export const LOAD_MORE_ACCOUNT_FAILED = "SRC/ACTIONS/LOAD_MORE_ACCOUNT_FAILED";